version: '3'
services:
  mssql:
    image: sashoristovski/mssql:latest
    container_name: mssql
    ports: 
      - "1433:1433"
    environment:
      SA_PASSWORD: "test1234!"
      ACCEPT_EULA: "Y"
  webapp:
    build: .
    depends_on:
      - mssql
    container_name: webapp
    ports:
      - "5000:80"